### ISSUE TITLE
ActionView::Template::Error (undefined method `identifier' for class Avo::PanelComponent)

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [avo-hq/avo#3281]
### Context

We're getting ActionView::Template::Error (undefined method `identifier' for class Avo::PanelComponent) error after bumping view_component version to 3.15.0
### System configuration
**Avo version**:
3.12.0
**Rails version**:
7.2.1
**Ruby version**:
3.3.4
**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

```
ActionView::Template::Error (undefined method `identifier' for class Avo::TurboFrameWrapperComponent):
  | 17:44:30 web.1  | [df3d3590-b9d1-43cd-8179-f79ecfb70427] 
  | 17:44:30 web.1  | Causes:
 | 17:44:30 web.1  | [df3d3590-b9d1-43cd-8179-f79ecfb70427] NoMethodError (undefined method `identifier' for class Avo::TurboFrameWrapperComponent)
  | 17:44:30 web.1  | [df3d3590-b9d1-43cd-8179-f79ecfb70427]     1: <%= render Avo::TurboFrameWrapperComponent.new(params[:turbo_frame]) do %>
  | 17:44:30 web.1  | [df3d3590-b9d1-43cd-8179-f79ecfb70427]     2:   <%= render @component.new(
  | 17:44:30 web.1  | [df3d3590-b9d1-43cd-8179-f79ecfb70427]     3:       resource: @resource,
  | 17:44:30 web.1  | [df3d3590-b9d1-43cd-8179-f79ecfb70427]     4:       resources: @resources,
  | 17:44:30 web.1  | [df3d3590-b9d1-43cd-8179-f79ecfb70427]   
  | 17:44:30 web.1  | [df3d3590-b9d1-43cd-8179-f79ecfb70427] view_component (3.15.0) lib/view_component/inline_template.rb:10:in `method_missing'
```

**Comment by Paul-Bob** [comment]
https://main.avodemo.com Is now using `view_component (3.15.0)`

Please share the reproduction steps on https://main.avodemo.com or a minimal reproduction repository.

There is an opened issue on `view_component` about this error. 
https://github.com/ViewComponent/view_component/issues/2106

**Comment by Paul-Bob** [comment]
This should be fixed on `view_component 3.15.1`
