### ISSUE TITLE
After update to v5.0: undefined local variable or method `by_position' for #<Avo::Hosts::AssociationScopeHost:0x0000ffff5aa90f10>

### ISSUE THREAD

**Issue by jony1993** [avo-hq/avo#879]
### Describe the bug
After update to v5.0: I get following error:
```
undefined local variable or method `by_position' for #<Avo::Hosts::AssociationScopeHost:0x0000ffff5aa90f10> 
```

v5.1 also not working.
v4.1 working

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

#### Impact

 - [ x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
I think I'll need a few more details. I don't see any string `by_position` in Avo's codebase.
Can you share a snippet of where you use it, and what it does?
Also, the line number of where that error is thrown?

**Comment by jony1993** [comment]
Hi Adrian,

Sorry for the late response.
After upgrading to v5.0 it seems that the resource scopes are not working anymore.
We have a lot of  has_many fields with scopes e.g.
```
 field :qualifications, as: :has_many, scope: -> { by_position }
 ```
 
 And all has_many resources with scopes could not be loaded in this >=5.0 versions

**Comment by jony1993** [comment]
@adrianthedev 
Thanks is working. Did not see the doc update...
