### ISSUE TITLE
Avo App Broken after upgrade to 2.3.0 - undefined method `items' for nil:NilClass (ActionView::Template::Error)

### ISSUE THREAD

**Issue by Reizar** [avo-hq/avo#866]
### Describe the bug

I recently updated to Avo 2.3.0 and have converted to using the new menu builder. ( Previously I had hard coded links in an ejected sidebar partial. I have deleted the sidebar partials now ).

When I try access any avo admin panel page, I'm getting this error.

Stacktrace:

```ruby
gems/avo-2.3.0components/avo/sidebar_component.html.erb:15:in `call': undefined method `items' for nil:NilClass (ActionView::Template::Error)
    from gems/view_component-2.53.0/lib/view_component/compiler.rb:132:in `render_template_for'
    from gems/view_component-2.53.0/lib/view_component/base.rb:116:in `perform_render'
    from gems/view_component-2.53.0/lib/view_component/base.rb:107:in `render_in'
    from gems/actionview-6.1.5/lib/action_view/helpers/rendering_helper.rb:43:in `render'
    from gems/avo-2.3.0views/layouts/avo/application.html.erb:26:in `__usr_local_bundle_ruby_______gems_avo_______app_views_layouts_avo_application_html_erb__761000985784817361_126480'
    from gems/actionview-6.1.5/lib/action_view/base.rb:247:in `public_send'
    from gems/actionview-6.1.5/lib/action_view/base.rb:247:in `_run'
    from gems/actionview-6.1.5/lib/action_view/template.rb:154:in `block in render'
    from gems/activesupport-6.1.5/lib/active_support/notifications.rb:205:in `instrument'
    from gems/actionview-6.1.5/lib/action_view/template.rb:345:in `instrument_render_template'
    from gems/actionview-6.1.5/lib/action_view/template.rb:152:in `render'
    from gems/actionview-6.1.5/lib/action_view/renderer/template_renderer.rb:72:in `block in render_with_layout'
    from gems/activesupport-6.1.5/lib/active_support/notifications.rb:205:in `instrument'
    from gems/actionview-6.1.5/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
    from gems/actionview-6.1.5/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
    from gems/actionview-6.1.5/lib/action_view/renderer/template_renderer.rb:11:in `render'
    from gems/actionview-6.1.5/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
    from gems/actionview-6.1.5/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
    from gems/actionview-6.1.5/lib/action_view/rendering.rb:117:in `block in _render_template'
    from gems/actionview-6.1.5/lib/action_view/base.rb:273:in `in_rendering_context'
    from gems/actionview-6.1.5/lib/action_view/rendering.rb:116:in `_render_template'
    from gems/actionpack-6.1.5/lib/action_controller/metal/streaming.rb:218:in `_render_template'
    from gems/actionview-6.1.5/lib/action_view/rendering.rb:103:in `render_to_body'
    from gems/actionpack-6.1.5/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
    from gems/actionpack-6.1.5/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
    from gems/actionpack-6.1.5/lib/abstract_controller/rendering.rb:25:in `render'
    from gems/actionpack-6.1.5/lib/action_controller/metal/rendering.rb:36:in `render'
    from gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
    from /usr/lib/fullstaq-ruby/versions/2.7.5-jemalloc/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
    from gems/activesupport-6.1.5/lib/active_support/core_ext/benchmark.rb:14:in `ms'
    from gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
    from gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
    from gems/activerecord-6.1.5/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
    from gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:45:in `render'
    from gems/meta-tags-2.16.0/lib/meta_tags/controller_helper.rb:22:in `render'
    from gems/avo-2.3.0controllers/avo/application_controller.rb:63:in `render'
    from gems/actionpack-6.1.5/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
    from gems/actionpack-6.1.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
    from gems/actionpack-6.1.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
    from gems/actionpack-6.1.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    from gems/actionpack-6.1.5/lib/abstract_controller/base.rb:228:in `process_action'
    from gems/actionpack-6.1.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
    from gems/actionpack-6.1.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    from gems/activesupport-6.1.5/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
    from gems/graphiti-rails-0.4.0/lib/graphiti/rails/debugging.rb:13:in `block in debug_graphiti'
    from gems/graphiti-1.3.6/lib/graphiti/debugger.rb:116:in `debug'
    from gems/graphiti-rails-0.4.0/lib/graphiti/rails/debugging.rb:12:in `debug_graphiti'
    from gems/activesupport-6.1.5/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
    from gems/graphiti-rails-0.4.0/lib/graphiti/rails/context.rb:17:in `block in wrap_graphiti_context'
    from gems/graphiti-1.3.6/lib/graphiti.rb:33:in `with_context'
    from gems/graphiti-rails-0.4.0/lib/graphiti/rails/context.rb:16:in `wrap_graphiti_context'
    from gems/activesupport-6.1.5/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
    from gems/activesupport-6.1.5/lib/active_support/callbacks.rb:137:in `run_callbacks'
    from gems/actionpack-6.1.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
    from gems/actionpack-6.1.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
    from gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    from gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `block in instrument'
    from gems/activesupport-6.1.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `instrument'
    from gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
    from gems/actionpack-6.1.5/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
    from gems/rescue_registry-1.0.0/lib/rescue_registry/controller.rb:24:in `process_action'
    from gems/activerecord-6.1.5/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
    from gems/actionpack-6.1.5/lib/abstract_controller/base.rb:165:in `process'
    from gems/actionview-6.1.5/lib/action_view/rendering.rb:39:in `process'
    from gems/actionpack-6.1.5/lib/action_controller/metal.rb:190:in `dispatch'
    from gems/actionpack-6.1.5/lib/action_controller/metal.rb:254:in `dispatch'
    from gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
    from gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:33:in `serve'
    from gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:50:in `block in serve'
    from gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:32:in `each'
    from gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:32:in `serve'
    from gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:842:in `call'
    from gems/railties-6.1.5/lib/rails/engine.rb:539:in `call'
    from gems/railties-6.1.5/lib/rails/railtie.rb:207:in `public_send'
    from gems/railties-6.1.5/lib/rails/railtie.rb:207:in `method_missing'
    from gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
    from gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:49:in `serve'
    from gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:50:in `block in serve'
    from gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:32:in `each'
    from gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:32:in `serve'
    from gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:842:in `call'
    from gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
    from gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/cookies.rb:689:in `call'
    from gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
    from gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
    from gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
    from gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
    from gems/rack-2.2.3/lib/rack/static.rb:161:in `call'
    from gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
    from gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
    from gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    from gems/activesupport-6.1.5/lib/active_support/callbacks.rb:98:in `run_callbacks'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
    from gems/bugsnag-6.24.2/lib/bugsnag/integrations/rack.rb:51:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    from gems/rescue_registry-1.0.0/lib/rescue_registry/action_dispatch/show_exceptions.rb:11:in `call'
    from gems/rescue_registry-1.0.0/lib/rescue_registry/reset_context.rb:9:in `call'
    from gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
    from gems/railties-6.1.5/lib/rails/rack/logger.rb:28:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    from gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/request_id.rb:26:in `call'
    from gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
    from gems/activesupport-6.1.5/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
    from gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
    from gems/actionpack-6.1.5/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
    from gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
    from gems/railties-6.1.5/lib/rails/engine.rb:539:in `call'
    from gems/puma-4.3.12/lib/puma/configuration.rb:228:in `call'
    from gems/puma-4.3.12/lib/puma/server.rb:727:in `handle_request'
    from gems/puma-4.3.12/lib/puma/server.rb:476:in `process_client'
    from gems/puma-4.3.12/lib/puma/server.rb:332:in `block in run'
    from gems/puma-4.3.12/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

### Steps to Reproduce
1. Go to any page in the Avo app.

### Expected behavior
Loads Avo App

### Actual behavior
Crashes with exception

### System configuration
**Avo version**: 2.3.0

**Rails version**: 6.1.5

**Ruby version**: 2.7.5

### Additional context
This only happens in production, in our development and staging environments the Avo App works fine. I have a valid license that is configured properly. And everything was working properly prior to upgrading to 2.3.0.

#### Impact

 - [✓ ] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [✓ ] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @Reizar. So you're saying that you have configured your `main_menu` and in development, you can see the menu, but in production, it crashes. 

Is that correct?

**Comment by adrianthedev** [comment]
I think I found a bug. Let me push a fix today.

**Comment by Reizar** [comment]
> Hey @Reizar. So you're saying that you have configured your `main_menu` and in development, you can see the menu, but in production, it crashes.
> 
> Is that correct?



> Hey @Reizar. So you're saying that you have configured your `main_menu` and in development, you can see the menu, but in production, it crashes.
> 
> Is that correct?
Hey @adrianthedev, Yes thats correct.


Thanks!

**Comment by Reizar** [comment]
> Hey @Reizar. So you're saying that you have configured your `main_menu` and in development, you can see the menu, but in production, it crashes.
> 
> Is that correct?



> Hey @Reizar. So you're saying that you have configured your `main_menu` and in development, you can see the menu, but in production, it crashes.
> 
> Is that correct?
Hey @adrianthedev, Yes thats correct.


Thanks!

**Comment by adrianthedev** [comment]
@Reizar https://github.com/avo-hq/avo/pull/867 should fix this bug too. Please update and try out the menu editor.

Thank you!

**Comment by Reizar** [comment]
@adrianthedev Awesome, that fixed it. Thanks so much for fixing this so quickly. Much appreciated :)

**Comment by Reizar** [comment]
@adrianthedev Awesome, that fixed it. Thanks so much for fixing this so quickly. Much appreciated :)
