### ISSUE TITLE
Record Ordering not working in Avo 2.10.2

### ISSUE THREAD

**Issue by jony1993** [avo-hq/avo#1066]
### Describe the bug
After updating from version 2.7.0 to 2.10.2 some of our associations could not be loaded.
After checking it, it seems that the record ordering of associations is causing this error.
Saw no breaking change regarding this in the avo docs

```
  self.ordering = {
    visible_on: :association,
    actions: {
      higher: -> { record.move_higher },
      lower: -> { record.move_lower },
      to_top: -> { record.move_to_top },
      to_bottom: -> { record.move_to_bottom }
    }
  }
  ```
  
I get following error
undefined method `associations_order_path' for #<ActionDispatch::Routing::RoutesProxy:0x0000ffff5d918428>

### Expected behavior & Actual behavior
Associations should be working

### Models and resource files
```
class CourseWhatYouGetResource < Avo::BaseResource
  self.model_class = Course::WhatYouGet
  ...
  self.ordering = {
    visible_on: :association,
    actions: {
      higher: -> { record.move_higher },
      lower: -> { record.move_lower },
      to_top: -> { record.move_to_top },
      to_bottom: -> { record.move_to_bottom }
    }
  }
  ...
end
```

```
class CourseResource < Avo::BaseResource
...
  field :what_you_gets, as: :has_many, scope: -> { query.by_position }
...
end
```

### System configuration
**Avo version**:
2.10.2

**Rails version**:
6.1.3

**Ruby version**:
2.7.2

**License type**:

 - [ ] Community
 - [x] Pro

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Yes, a bug was introduced at some point that broke it. [This](https://github.com/avo-hq/avo/pull/1053) PR should fix it in today's release.

Closing for now, but please feel free to reopen if needed.
