### ISSUE TITLE
undefined method `avo_dashboards' for an instance of #<Class:0x000000013abba3d8>

### ISSUE THREAD

**Issue by smathieu** [avo-hq/avo#3747]
### Describe the bug

Dashboards raising exception after upgrade to 3.17.9 to 3.18.1

### Reproduction repository for the bug

I'm not sure how to reproduce outside of our repo, but happy to provide context as needed.

### Steps to use in the reproduction repository
1. Add this configuration '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

### System configuration
**Avo version**:

**Rails version**:
8.0.1

**Ruby version**:
3.3.6
**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [x] Yes. But nothing related to dashboards.
 - [ ] No

### Additional context

```
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/engine/lazy_route_set.rb:99:in `method_missing'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-menu-3.18.1/app/components/avo/sidebar/item_switcher_component.html.erb:8:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/compiler.rb:98:in `render_template_for'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/base.rb:111:in `render_in'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/base.rb:208:in `render'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/components/avo/sidebar/section_component.html.erb:16:in `block (2 levels) in call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/components/avo/sidebar/section_component.html.erb:15:in `each'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/components/avo/sidebar/section_component.html.erb:15:in `block in call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/components/avo/sidebar/section_component.html.erb:10:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/compiler.rb:98:in `render_template_for'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/base.rb:111:in `render_in'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/base.rb:208:in `render'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-menu-3.18.1/app/components/avo/sidebar/item_switcher_component.html.erb:11:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/compiler.rb:98:in `render_template_for'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/base.rb:111:in `render_in'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/base.rb:208:in `render'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/components/avo/sidebar_component.html.erb:17:in `block (2 levels) in call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/components/avo/sidebar_component.html.erb:16:in `each'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/components/avo/sidebar_component.html.erb:16:in `block in call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/components/avo/sidebar_component.html.erb:1:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/compiler.rb:98:in `render_template_for'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/view_component-3.21.0/lib/view_component/base.rb:111:in `render_in'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/views/layouts/avo/application.html.erb:35:in `___sers_smathieu__gem_ruby_______gems_avo________app_views_layouts_avo_application_html_erb__1602563519808162107_141100'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/meta-tags-2.22.1/lib/meta_tags/controller_helper.rb:22:in `render'
     # ./app/models/actor.rb:45:in `with'
     # ./app/controllers/concerns/controller_with_actor.rb:11:in `with_actor'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/i18n-1.14.7/lib/i18n.rb:353:in `with_locale'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/avo-3.18.1/app/controllers/avo/base_application_controller.rb:271:in `set_avo_locale'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/turbo-rails-2.0.13/lib/turbo-rails.rb:24:in `with_request_id'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/turbo-rails-2.0.13/app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-rails-5.22.4/lib/sentry/rails/controller_transaction.rb:34:in `block in sentry_around_action'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry/hub.rb:108:in `with_child_span'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry-ruby.rb:507:in `with_child_span'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-rails-5.22.4/lib/sentry/rails/controller_transaction.rb:18:in `sentry_around_action'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/engine/lazy_route_set.rb:68:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/engine.rb:535:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/railtie.rb:226:in `public_send'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/railtie.rb:226:in `method_missing'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/engine/lazy_route_set.rb:68:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/flipper-1.3.3/lib/flipper/middleware/memoizer.rb:87:in `memoized_call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/flipper-1.3.3/lib/flipper/middleware/memoizer.rb:45:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:470:in `call_app!'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-saml-2.2.2/lib/omniauth/strategies/saml.rb:86:in `other_phase'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:195:in `call!'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:202:in `call!'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:202:in `call!'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/omniauth-2.1.2/lib/omniauth/builder.rb:44:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/scout_apm-5.6.1/lib/scout_apm/middleware.rb:17:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/warden-jwt_auth-0.10.0/lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/warden-jwt_auth-0.10.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/builder.rb:244:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/warden-jwt_auth-0.10.0/lib/warden/jwt_auth/middleware.rb:22:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/static.rb:162:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/static.rb:162:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/static.rb:162:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/tempfile_reaper.rb:15:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/etag.rb:27:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/conditional_get.rb:27:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/head.rb:12:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/session/abstract/id.rb:266:in `context'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/session/abstract/id.rb:260:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-rails-5.22.4/lib/sentry/rails/rescued_exception_interceptor.rb:14:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry/rack/capture_exceptions.rb:30:in `block (2 levels) in call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry/hub.rb:269:in `with_session_tracking'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry-ruby.rb:420:in `with_session_tracking'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry/rack/capture_exceptions.rb:21:in `block in call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry/hub.rb:59:in `with_scope'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry-ruby.rb:400:in `with_scope'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/sentry-ruby-5.22.4/lib/sentry/rack/capture_exceptions.rb:20:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/rack/logger.rb:41:in `call_app'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/rack/logger.rb:29:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/method_override.rb:24:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/runtime.rb:22:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/judoscale-ruby-1.10.0/lib/judoscale/request_middleware.rb:41:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-2.2.13/lib/rack/sendfile.rb:110:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/engine.rb:535:in `call'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-test-2.2.0/lib/rack/test.rb:360:in `process_request'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/rack-test-2.2.0/lib/rack/test.rb:153:in `request'
     # ./spec/requests/avo/integration_spec.rb:33:in `block (5 levels) in <top (required)>'
     # ./spec/rails_helper.rb:110:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:97:in `block (3 levels) in <top (required)>'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/database_cleaner-core-2.0.1/lib/database_cleaner/strategy.rb:30:in `cleaning'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:34:in `block (2 levels) in cleaning'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:35:in `cleaning'
     # ./spec/rails_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./spec/support/prosopite.rb:73:in `block (3 levels) in <main>'
     # ./spec/support/prosopite.rb:21:in `block in scan'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/prosopite-2.1.0/lib/prosopite.rb:63:in `scan'
     # ./spec/support/prosopite.rb:20:in `scan'
     # ./spec/support/prosopite.rb:73:in `block (2 levels) in <main>'
     # /Users/smathieu/.gem/ruby/3.3.6/gems/webmock-3.25.0/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `avo_dashboards' for an instance of #<Class:0x000000013abba3d8>
     #   /Users/smathieu/.gem/ruby/3.3.6/gems/railties-8.0.1/lib/rails/engine/lazy_route_set.rb:99:in `method_missing'

```

#### Impact
Can't upgrade.

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hi @smathieu, thanks for reaching out!

This is a known breaking change. Please refer to [the documentation](https://docs.avohq.io/3.0/upgrade.html#Avo's%20mounting%20point%20update) for the necessary upgrade steps.

I recommend reviewing the upgrade guide for each minor update. While breaking changes are rare, we always document them there when they occur.

Let me know how it goes and if you have any questions!
