### ISSUE TITLE
rails 7.1.0.alpha - NoMethodError (undefined method `table_name' for #<Arel::Table

### ISSUE THREAD

**Issue by yshmarov** [avo-hq/avo#1821]
### Describe the bug

avo ransack search does not seem to be working on rails 7.1.0alpha. works on lower versions. wanted to let you know just in case it's relevant

<img width="1165" alt="Screenshot 2023-07-02 at 12 37 36" src="https://github.com/avo-hq/avo/assets/13472945/ef7b8902-08c4-41d4-a4ed-38d5cc7e6864">

### System configuration
**Avo version**:
2.3.5
**Rails version**:
7.1.0.alpha
**Ruby version**:
3.2.2
**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
This is weird. I just created a new app and it seems to work.
![CleanShot 2023-07-02 at 19 43 05](https://github.com/avo-hq/avo/assets/1334409/ff741510-1981-43dc-b111-8e6d1b2ffb61)

**Comment by adrianthedev** [comment]
Are you using search from the resource page (/users)?
