### PR TITLE
refactor: register actions from show_controls

### LINKED ISSUE #1443: Actions added in show_controls block don't work in avo 2.20
### Describe the bug

I have two resources that use a `show_controls` block to customise the buttons shown to the user, some of which are standard buttons (like edit and delete) and some are actions. These actions worked in avo 2.19 and before, but since upgrading to avo 2.20 clicking the actions does nothing and raises this error in the logs:

```
10:37:17 web.1     | NoMethodError (undefined method `[]' for nil:NilClass
10:37:17 web.1     |
10:37:17 web.1     |       action[:arguments]
10:37:17 web.1     |             ^^^^^^^^^^^^):
10:37:17 web.1     |
10:37:17 web.1     | avo (2.20.0) lib/avo/base_resource.rb:190:in `get_action_arguments'
10:37:17 web.1     | avo (2.20.0) app/controllers/avo/actions_controller.rb:59:in `set_action'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:400:in `block in make_lambda'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:180:in `block (2 levels) in halting_and_conditional'
10:37:17 web.1     | actionpack (7.0.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:181:in `block in halting_and_conditional'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `block in invoke_before'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `each'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `invoke_before'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
10:37:17 web.1     | i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
10:37:17 web.1     | avo (2.20.0) app/controllers/avo/application_controller.rb:330:in `set_avo_locale'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
10:37:17 web.1     | actiontext (7.0.4) lib/action_text/rendering.rb:20:in `with_renderer'
10:37:17 web.1     | actiontext (7.0.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `instance_exec'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:138:in `run_callbacks'
10:37:17 web.1     | actionpack (7.0.4) lib/abstract_controller/callbacks.rb:233:in `process_action'
10:37:17 web.1     | actionpack (7.0.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
10:37:17 web.1     | actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
10:37:17 web.1     | actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
10:37:17 web.1     | actionpack (7.0.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
10:37:17 web.1     | activerecord (7.0.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
10:37:17 web.1     | actionpack (7.0.4) lib/abstract_controller/base.rb:151:in `process'
10:37:17 web.1     | actionview (7.0.4) lib/action_view/rendering.rb:39:in `process'
10:37:17 web.1     | actionpack (7.0.4) lib/action_controller/metal.rb:188:in `dispatch'
10:37:17 web.1     | actionpack (7.0.4) lib/action_controller/metal.rb:251:in `dispatch'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
10:37:17 web.1     | railties (7.0.4) lib/rails/engine.rb:530:in `call'
10:37:17 web.1     | railties (7.0.4) lib/rails/railtie.rb:226:in `public_send'
10:37:17 web.1     | railties (7.0.4) lib/rails/railtie.rb:226:in `method_missing'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
10:37:17 web.1     | config/initializers/x_robots_tag.rb:7:in `call'
10:37:17 web.1     | warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
10:37:17 web.1     | warden (1.2.9) lib/warden/manager.rb:34:in `catch'
10:37:17 web.1     | warden (1.2.9) lib/warden/manager.rb:34:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/static.rb:161:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/etag.rb:27:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/head.rb:12:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
10:37:17 web.1     | rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
10:37:17 web.1     | activerecord (7.0.4) lib/active_record/migration.rb:603:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
10:37:17 web.1     | bugsnag (6.24.2) lib/bugsnag/integrations/rack.rb:51:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
10:37:17 web.1     | web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
10:37:17 web.1     | web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
10:37:17 web.1     | web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
10:37:17 web.1     | web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
10:37:17 web.1     | railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
10:37:17 web.1     | railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
10:37:17 web.1     | railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
10:37:17 web.1     | sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
10:37:17 web.1     | request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/method_override.rb:24:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/runtime.rb:22:in `call'
10:37:17 web.1     | activesupport (7.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
10:37:17 web.1     | rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
10:37:17 web.1     | actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
10:37:17 web.1     | railties (7.0.4) lib/rails/engine.rb:530:in `call'
10:37:17 web.1     | puma (5.6.5) lib/puma/configuration.rb:252:in `call'
10:37:17 web.1     | puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
10:37:17 web.1     | puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
10:37:17 web.1     | puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
10:37:17 web.1     | puma (5.6.5) lib/puma/server.rb:443:in `process_client'
10:37:17 web.1     | puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

Debugging the code it looks like `BaseResource.get_actions()` is an empty array (because `BaseResource::actions_loader` is `nil`). I think this is happening because I haven't called `action` in my resources - if I explicitly add `action` (outside the show controls block) then it works again (but this wasn't necessary before). Should calling `action` inside `show_controls` also register the action?

### Steps to Reproduce
1. Create a new resource and an action
2. Add `self.show_controls = -> { action MyAction }` to the resource 
3. Browse to the resource in avo, and then click on the action
4. Nothing visible happens, if you look in the logs you should see the error

### Expected behavior & Actual behavior

The action should execute, but instead nothing happens and there's an error in the server logs.

### System configuration
**Avo version**: 2.20

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #1443

actions_index

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

File: app/components/avo/views/resource_show_component.html.erb [hunk 1]
```diff
@@ -10,89 +10,116 @@
   <%= render Avo::PanelComponent.new(name: title, description: @resource.resource_description, display_breadcrumbs: @reflection.blank?, index: 0, data: { panel_id: "main" }) do |c| %>
```
Comment (Paul-Bob) [inline app/components/avo/views/resource_show_component.html.erb:10]: @adrianthedev this file was refactored in order to make first iteration of index on actions work. I found out we do not need it like this anymore, do you prefer to keep it like this or revert this changes?

**Comment by adrianthedev** [comment]
This PR is getting kinda large.

Here's something crazy. How about we just mention to users in the documentation that they have to register the action in order to use it in the `show_controls` and we fix this in Avo 3?
I'd rather get more things done in v3 rather than spend too much time in v2.

**Comment by Paul-Bob** [comment]
> This PR is getting kinda large.
> 
> Here's something crazy. How about we just mention to users in the documentation that they have to register the action in order to use it in the `show_controls` and we fix this in Avo 3? I'd rather get more things done in v3 rather than spend too much time in v2.

I agree, this PR it's made on a fragile foundation. We should rethink the whole actions architecture and make it robust on Avo 3.
