### ISSUE TITLE
Issue with `to_sql` after upgrading to 2.14.1

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1196]
### Context
After upgrading to 2.14.1, I'm getting the error below:

```13:02:45 web.1  |   Rendered /home/allskar.linux/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/avo-2.14.1/app/views/avo/base/index.html.erb within layouts/avo/application (Duration: 17.5ms | Allocations: 14402)
13:02:45 web.1  |   Rendered layout /home/allskar.linux/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/avo-2.14.1/app/views/layouts/avo/application.html.erb (Duration: 18.1ms | Allocations: 14505)
13:02:45 web.1  | Completed 500 Internal Server Error in 842ms (ActiveRecord: 9.9ms | Allocations: 29200)
13:02:45 web.1  |
13:02:45 web.1  |
13:02:45 web.1  |
13:02:45 web.1  | ActionView::Template::Error (undefined method `to_sql' for Company:Class
13:02:45 web.1  | Did you mean?  to_s):
13:02:45 web.1  |     1: <%= render Avo::TurboFrameWrapperComponent.new(params[:turbo_frame]) do %>
13:02:45 web.1  |     2:   <%= render Avo::Views::ResourceIndexComponent.new(
13:02:45 web.1  |     3:       resource: @resource,
13:02:45 web.1  |     4:       resources: @resources,
13:02:45 web.1  |     5:       models: @models,
13:02:45 web.1  |
13:02:45 web.1  | activerecord (7.0.3.1) lib/active_record/dynamic_matchers.rb:22:in `method_missing'
13:02:45 web.1  | avo (2.14.1) app/components/avo/index/resource_table_component.rb:21:in `encrypted_query'
13:02:45 web.1  | avo (2.14.1) app/components/avo/index/resource_table_component.html.erb:5:in `call'
13:02:45 web.1  | view_component (2.60.0) lib/view_component/compiler.rb:130:in `block in render_template_for'
```

I've followed the upgrade guides from 2.11 to 2.12/2.13/2.14: https://docs.avohq.io/2.0/upgrade.html

### System configuration
**Avo version**: 2.14.1

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type** (Community or Pro): Pro

### Screenshots
![image](https://user-images.githubusercontent.com/575138/187689203-9aca58ad-907e-4fcd-888e-7b8778c984e2.png)

**Comment by adrianthedev** [comment]
Hey @alansikora. Thanks for the bug report! It would help us a lot if you'd follow [the guides on the bug report template](https://github.com/avo-hq/avo/issues/new?assignees=&labels=&template=bug_report.md&title=) and give us all the information on the first go. Otherwise, we're always going to ask you for those details 🙂

Can you please the steps for reproduction?

**Comment by adrianthedev** [comment]
Hmmm, I see that the details from the issue are in the code block.

Can you share on what page are you currently on, and how you got there?

**Comment by alansikora** [comment]
Sorry, I ended the code with ``` on the same line, my bad.

**Comment by alansikora** [comment]
> Hey @alansikora. Thanks for the bug report! It would help us a lot if you'd follow [the guides on the bug report template](https://github.com/avo-hq/avo/issues/new?assignees=&labels=&template=bug_report.md&title=) and give us all the information on the first go. Otherwise, we're always going to ask you for those details 🙂
> 
> Can you please share the steps for reproduction?

Sorry, I ended the code with ``` on the same line, my bad.

**Comment by adrianthedev** [comment]
All good. I noticed after the fact. Where do you get this error? On what page?

**Comment by alansikora** [comment]
> All good. I noticed after the fact. Where do you get this error? On what page?


https://user-images.githubusercontent.com/575138/187693771-3220e0fe-bb06-4ea6-9110-a1125b4c4cd9.mp4

Looks like all the resources but `Users` area breaking.

I believe it might be related to the fact that all those resources are on a different Postgres schema, so I declare them like:

![image](https://user-images.githubusercontent.com/575138/187693977-0d72bdbb-6903-43b6-8776-092a9fe05bbf.png)

**Comment by adrianthedev** [comment]
@alansikora please try this version and let me know.

https://rubygems.org/gems/avo/versions/2.14.3.pre.4.tosqlfix

**Comment by alansikora** [comment]
> @alansikora please try this version and let me know.
> 
> https://rubygems.org/gems/avo/versions/2.14.3.pre.4.tosqlfix

It works @adrianthedev !

Let me know if I can help you with this issue.

**Comment by adrianthedev** [comment]
Perfect 🙌 Please use this version until we release it stable in two weeks.

**Comment by alansikora** [comment]
Sure thing!
